# Generated by Django 3.2.7 on 2023-01-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
    ]
